const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{EventEmitter}=require('node:events');
const {localUrl,allowedExternal}=require('../desktop/policy.cjs');
test('desktop navigation and IPC origin policy reject external and deceptive URLs',()=>{const o='http://127.0.0.1:8080';assert.ok(localUrl(o+'/wiki/index.html',o));for(const u of ['http://127.0.0.1:8081/','http://127.0.0.1.attacker.test:8080/','file:///C:/test','javascript:alert(1)'])assert.equal(localUrl(u,o),false);assert.ok(allowedExternal('https://github.com/olegbl/d2rmm/releases'));for(const u of ['file:///C:/Windows/cmd.exe','http://github.com/','https://github.com.attacker.test/','https://user@github.com/'])assert.equal(allowedExternal(u),false);});
test('desktop window lifecycle uses sandbox, singleton, fixed origin, controlled child windows and cleanup',async()=>{
 const app=new EventEmitter();let quits=0;Object.assign(app,{setName(){},setAppUserModelId(){},requestSingleInstanceLock:()=>true,whenReady:async()=>{},quit(){quits++}});const windows=[],handlers={},external=[];let closeCount=0;const server=new EventEmitter();server.listen=(_p,_h,cb)=>cb();
 class Window extends EventEmitter{constructor(opts){super();this.opts=opts;windows.push(this);this.webContents=new EventEmitter();this.webContents.getURL=()=>this.url||'';this.webContents.setWindowOpenHandler=f=>this.openHandler=f;this.destroyed=false;this.minimized=false;}setMenu(){}async loadURL(url){this.url=url;this.emit('ready-to-show')}show(){this.shown=true}focus(){this.focused=true}minimize(){this.minimized=true}isMinimized(){return this.minimized}restore(){this.minimized=false}isDestroyed(){return this.destroyed}destroy(){this.destroyed=true;this.emit('closed')}isMaximized(){return false}maximize(){}unmaximize(){}}
 const electron={app,BrowserWindow:Window,ipcMain:{handle:(k,f)=>handlers[k]=f},dialog:{showErrorBox(){},showMessageBox:async()=>({response:1})},session:{defaultSession:{setPermissionRequestHandler(){},setPermissionCheckHandler(){}}},shell:{openExternal:async x=>external.push(x)},screen:{getPrimaryDisplay:()=>({workAreaSize:{width:1920,height:1080}})}};
 const context={require:n=>n==='electron'?electron:n==='../scripts/serve-editor.cjs'?{createSuite:()=>({server,close:async()=>closeCount++})}:n==='./policy.cjs'?{localUrl,allowedExternal}:require(n),__dirname:path.resolve(__dirname,'../desktop'),console};
 vm.runInNewContext(fs.readFileSync(path.resolve(__dirname,'../desktop/main.cjs'),'utf8'),context);await new Promise(r=>setImmediate(r));const w=windows[0];assert.ok(w);assert.equal(w.opts.frame,false);assert.equal(w.opts.webPreferences.nodeIntegration,false);assert.equal(w.opts.webPreferences.contextIsolation,true);assert.equal(w.opts.webPreferences.sandbox,true);assert.equal(w.url,'http://127.0.0.1:8080/');
 app.emit('second-instance');assert.ok(w.focused);assert.equal(w.openHandler({url:'http://127.0.0.1:8080/wiki/index.html'}).action,'deny');assert.equal(windows.length,2);assert.equal(windows[1].opts.webPreferences.preload,undefined);
 w.openHandler({url:'file:///C:/bad.exe'});assert.equal(external.length,0);
 const f=handlers['d2plus-window'];await assert.rejects(()=>f({sender:windows[1].webContents,senderFrame:{url:w.url}},'close'),/rejected/);await f({sender:w.webContents,senderFrame:{url:w.url}},'minimize');assert.ok(w.minimized);
 w.emit('close',{preventDefault(){}});await new Promise(r=>setImmediate(r));assert.equal(closeCount,1);assert.ok(w.destroyed);assert.ok(windows[1].destroyed);assert.equal(quits,1);
});
