const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {JSDOM}=require('jsdom');const {Launcher,VERSION}=require('../scripts/launcher-core.cjs');const os=require('node:os');
const root=path.resolve(__dirname,'..');
test('wizard imports, preserves edits during polling, saves steps, reloads and keeps reference features available',async t=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'wizard settings '));t.after(()=>fs.rmSync(temp,{recursive:true,force:true}));const adapter={platform:'win32',async validateFiles(c){if(!c.gameExe)throw Error('No game')},async inspectExe(){return {fileVersion:'Mock 1.2.3',productVersion:'Mock'}},async stopCompanion(){}};let l=new Launcher({adapter,suiteRoot:root,settingsFile:path.join(temp,'settings.json')});
 const options={runScripts:'outside-only',url:'http://127.0.0.1:8080/'};let dom;const requests=[];
 async function open(){dom=new JSDOM(fs.readFileSync(path.join(root,'docs/launcher/index.html'),'utf8'),options);const w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.setInterval=fn=>{w.__poll=fn;return 0};w.fetch=async(url,opt)=>{const action=url.split('/').pop();let data={},r;if(opt?.body)data=JSON.parse(opt.body);requests.push({action,data});try{switch(action){case 'status':r={...l.snapshot(),token:'test',setup:{}};break;case 'settings':if(w.rejectSave)throw Error('Simulated disk write failure');r=await l.save(data);break;case 'pick':r={path:'C:\\Shortcut Files\\D2PLUS.lnk'};break;case 'import-shortcut':r={gameExe:'C:\\Game With Spaces\\D2R.exe',workingDirectory:'C:\\Game With Spaces',modDirectory:'C:\\Game With Spaces\\mods\\Special Output',arguments:'-mod "Special Output" -txt -w -custom "keep me"'};break;case 'setup-check':r={gameReady:!!l.config.gameExe,gameError:'Select game',wikiReady:true,editorReady:true,companionReady:true};break;case 'inspect':r=await l.inspect();break;case 'stop':r=await l.disable();break;default:r={};}return{ok:true,json:async()=>r};}catch(e){return{ok:false,json:async()=>({error:e.message})}}};w.eval(fs.readFileSync(path.join(root,'docs/launcher/app.js'),'utf8'));await settle();return w;}
 async function settle(){await new Promise(r=>setTimeout(r,30));}
 let w=await open(),d=w.document;assert.ok(d.querySelector('#wizard').open,d.querySelector('#connection').textContent);
 const click=async id=>{d.querySelector(id).click();await settle();};
 await click('#next');await click('#importShortcut');const imported=d.querySelector('#arguments').value;assert.equal(imported,'-mod "Special Output" -txt -w -custom "keep me"');d.querySelector('#workingDirectory').value='C:\\Typed Path\\Keep This';d.querySelector('#workingDirectory').dispatchEvent(new w.Event('input'));await w.__poll();assert.equal(d.querySelector('#workingDirectory').value,'C:\\Typed Path\\Keep This');
 await click('#next');await click('#next');await click('#next');await click('#next');assert.equal(d.querySelector('#wizard').open,false);assert.equal(l.config.setupComplete,true);assert.equal(l.config.arguments,imported);assert.equal(l.config.workingDirectory,'C:\\Typed Path\\Keep This');
 dom.window.close();l=new Launcher({adapter,suiteRoot:root,settingsFile:path.join(temp,'settings.json')});w=await open();d=w.document;assert.equal(d.querySelector('#wizard').open,false);assert.equal(d.querySelector('#arguments').value,imported);
 await click('#enableDamageNumbers');assert.equal(l.config.enableDamageNumbers,true);await click('#stop');assert.equal(l.config.enableDamageNumbers,false);assert.equal(d.querySelector('#enableDamageNumbers').checked,false);
 await click('[data-view="install"]');assert.equal(d.querySelector('#install').hidden,false);assert.equal(d.querySelector('#home').hidden,true);assert.ok(d.querySelector('a[href="/wiki/index.html"]'));assert.ok(d.querySelector('a[href="/index.html"]'));
 // Save failure must keep input, show an error and leave setup open.
 await click('#setupOpen');w.rejectSave=true;d.querySelector('#gameExe').value='C:\\Still Typed\\D2R.exe';await click('#next');assert.equal(d.querySelector('#wizardError').hidden,false);assert.equal(d.querySelector('#gameExe').value,'C:\\Still Typed\\D2R.exe');assert.equal(d.querySelector('#wizard').open,true);
 dom.window.close();
});
